CREATE DATABASE donations;
COMMENT ON DATABASE donations IS 'This database is used for managing the Donation application data, including Donation transactions that are stored in a central fact table with auxillary information like donors, events, campaigns and payment method stored in other tables, plus other related entities.';

DROP TABLE IF EXISTS donor CASCADE;
-- Creating the donor table
CREATE TABLE donor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,  -- The unique identifier for this record
    firstname VARCHAR(255) NOT NULL,  -- The first name associated with this entity
    lastname VARCHAR(255) NOT NULL,  -- The last name associated with this entity
    email VARCHAR(255) NOT NULL,  -- The email associated with this entity
    phone VARCHAR(255) NOT NULL,  -- The phone number associated with this entity
    address VARCHAR(255) NOT NULL,  -- The address associated with this entity
    joindate TIMESTAMP,  -- The date the donor joined the organization
    donorstatus VARCHAR(255),  -- The current state of the entity (e.g., current, past, prospect)
    PRIMARY KEY (id)
);

COMMENT ON COLUMN donor.id IS 'The unique identifier for this record';
COMMENT ON COLUMN donor.firstname IS 'The first name associated with this entity';
COMMENT ON COLUMN donor.lastname IS 'The last name associated with this entity';
COMMENT ON COLUMN donor.email IS 'The email associated with this entity';
COMMENT ON COLUMN donor.phone IS 'The phone number associated with this entity';
COMMENT ON COLUMN donor.address IS 'The address associated with this entity';
COMMENT ON COLUMN donor.joindate IS 'The date the donor joined the organization';
COMMENT ON COLUMN donor.donorstatus IS 'The current state of the entity (e.g., current, past, prospect)';
COMMENT ON TABLE donor IS 'Table storing donor information';

DROP TABLE IF EXISTS campaign CASCADE;
-- Creating the campaign table
CREATE TABLE campaign (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,  -- The unique identifier for this record
    campaignname VARCHAR(255),  -- The campaign name associated with this record
    startdate TIMESTAMP,  -- The start date for the campaign
    enddate TIMESTAMP,  -- The end date for the campaign
    campaigntype VARCHAR(255),  -- The type of campaign (e.g. go-fund-me, outreach)
    targetamount DECIMAL(19,4),  -- The target amount of the campaign in dollars
    PRIMARY KEY (id)
);

COMMENT ON COLUMN campaign.id IS 'The unique identifier for this record';
COMMENT ON COLUMN campaign.campaignname IS 'The name of the campaign';
COMMENT ON COLUMN campaign.startdate IS 'The date the campaign started';
COMMENT ON COLUMN campaign.enddate IS 'The date the campaign ends';
COMMENT ON COLUMN campaign.campaigntype IS 'The type of campaign (e.g. go-fund-me, outreach)';
COMMENT ON COLUMN campaign.targetamount IS 'The target amount of the campaign in dollars';
COMMENT ON TABLE campaign IS 'Table storing campaign information';

DROP TABLE IF EXISTS datekey CASCADE;
-- Creating the datekey table
CREATE TABLE datekey (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,  -- The unique identifier for this record
    day SMALLINT NOT NULL,  -- The day of the date
    month SMALLINT NOT NULL,  -- The month of the date
    year SMALLINT NOT NULL,  -- The year of the date
    quarter SMALLINT NOT NULL,  -- The quarter of the date
    isholiday BOOLEAN,  -- Indicator if the date is a holiday (true/false)
    PRIMARY KEY (id)
);

COMMENT ON COLUMN datekey.id IS 'The unique identifier for this address record';
COMMENT ON COLUMN datekey.day IS 'The day of the date'; 
COMMENT ON COLUMN datekey.month IS 'The month of the date';
COMMENT ON COLUMN datekey.year IS 'The year of the date';
COMMENT ON COLUMN datekey.quarter IS 'The quarter of the date';
COMMENT ON COLUMN datekey.isholiday IS 'Indicator if the date is a holiday (true/false)';
COMMENT ON TABLE datekey IS 'Table storing the date of the donation information';


DROP TABLE IF EXISTS "event" CASCADE;
-- Creating the event table
CREATE TABLE "event" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,  -- The unique identifier for this record
    eventname VARCHAR(255),  -- The name of the event
    eventdate TIMESTAMP,  -- The date of the event
    eventlocation VARCHAR(255),  -- The location of the event
    eventtype VARCHAR(255),  -- The type of event (e.g., fundraiser, outreach)
    PRIMARY KEY (id)
); 

COMMENT ON COLUMN "event".id IS 'The unique identifier for this record';
COMMENT ON COLUMN "event".eventname IS 'The name of the event';
COMMENT ON COLUMN "event".eventdate IS 'The date of the event';
COMMENT ON COLUMN "event".eventlocation IS 'The location of the event';
COMMENT ON COLUMN "event".eventtype IS 'The type of event (e.g., fundraiser, outreach)';
COMMENT ON TABLE "event" IS 'Table storing event information';


DROP TABLE IF EXISTS "paymentmethod" CASCADE;
-- Creating the paymentmethod table
CREATE TABLE "paymentmethod" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,  -- The unique identifier for this record
    paymentmethodname VARCHAR(255),  -- The name of the payment method
    PRIMARY KEY (id)
);

COMMENT ON COLUMN "paymentmethod".id IS 'The unique identifier for this record';
COMMENT ON COLUMN "paymentmethod".paymentmethodname IS 'The name of the payment method';
COMMENT ON TABLE "paymentmethod" IS 'Table storing payment method information';

DROP TABLE IF EXISTS dimdonation CASCADE;
-- Creating the dimdonationfact table
CREATE TABLE dimdonation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    donationamount DECIMAL(19,4),
    donor BIGINT,           -- Add the column for donor
    campaign BIGINT,        -- Add the column for campaign
    datekey BIGINT,         -- Add the column for datekey
    paymentmethod BIGINT,   -- Add the column for paymentmethod
    event BIGINT,           -- Add the column for event
    PRIMARY KEY (id),
    FOREIGN KEY (donor) REFERENCES donor(id) ON DELETE SET NULL,
    FOREIGN KEY (campaign) REFERENCES campaign(id) ON DELETE SET NULL,
    FOREIGN KEY (datekey) REFERENCES datekey(id) ON DELETE SET NULL,
    FOREIGN KEY (paymentmethod) REFERENCES paymentmethod(id) ON DELETE SET NULL,
    FOREIGN KEY (event) REFERENCES event(id) ON DELETE SET NULL
);

COMMENT ON COLUMN dimdonation.id IS 'The unique identifier for this record';
COMMENT ON COLUMN dimdonation.donationamount IS 'The amount of the donation in dollars';
COMMENT ON TABLE dimdonation IS 'Table storing dimdonation information';
